"""initial schema

Revision ID: 70306c652a86
Revises: 
Create Date: 2026-10-07 21:53:31.815769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70306c652a86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executives'))
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'tailor', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_phone'), ['phone'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('promo_title', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('measurement_fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('slug', name=op.f('uq_services_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'tailor', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('role', 'phone', name='uq_users_role_phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('option_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('choice', 'toggle', name='optiongroupkind', native_enum=False, length=32), nullable=False),
    sa.Column('toggle_price', sa.Integer(), nullable=False),
    sa.Column('default_on', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_option_groups_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_groups'))
    )
    with op.batch_alter_table('option_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_groups_service_id'), ['service_id'], unique=False)

    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_packages_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages'))
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_service_id'), ['service_id'], unique=False)

    op.create_table('tailors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', name='tailorstatus', native_enum=False, length=32), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shop_name', sa.String(length=160), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('bank_account_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account_number', sa.String(length=34), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('open_time', sa.String(length=5), nullable=False),
    sa.Column('close_time', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tailors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tailors')),
    sa.UniqueConstraint('user_id', name=op.f('uq_tailors_user_id'))
    )
    with op.batch_alter_table('tailors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tailors_status'), ['status'], unique=False)

    op.create_table('kyc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tailor_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('aadhaar', 'pan', 'business_proof', 'bank_details', name='kycdoctype', native_enum=False, length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailors.id'], name=op.f('fk_kyc_documents_tailor_id_tailors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_documents')),
    sa.UniqueConstraint('tailor_id', 'doc_type', name='uq_kyc_documents_tailor_doc')
    )
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_documents_tailor_id'), ['tailor_id'], unique=False)

    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price_delta', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['option_groups.id'], name=op.f('fk_options_group_id_option_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_options'))
    )
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_options_group_id'), ['group_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1251), nullable=False),
    sa.Column('status', sa.Enum('placed', 'assigned', 'accepted', 'measurement_done', 'stitching', 'ready', 'delivered', 'cancelled', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('tailor_id', sa.Integer(), nullable=True),
    sa.Column('executive_id', sa.Integer(), nullable=True),
    sa.Column('customizations', sa.JSON(), nullable=False),
    sa.Column('measurement_method', sa.Enum('self', 'visit', name='measurementmethod', native_enum=False, length=32), nullable=False),
    sa.Column('measurement_unit', sa.String(length=4), nullable=True),
    sa.Column('measurements', sa.JSON(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('visit_slot', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('package_price', sa.Integer(), nullable=False),
    sa.Column('customization_price', sa.Integer(), nullable=False),
    sa.Column('visit_fee', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_orders_customer_id_users')),
    sa.ForeignKeyConstraint(['executive_id'], ['executives.id'], name=op.f('fk_orders_executive_id_executives')),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_orders_package_id_packages')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_orders_service_id_services')),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailors.id'], name=op.f('fk_orders_tailor_id_tailors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_executive_id'), ['executive_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tailor_id'), ['tailor_id'], unique=False)

    op.create_table('tailor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tailor_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_tailor_prices_package_id_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailors.id'], name=op.f('fk_tailor_prices_tailor_id_tailors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tailor_prices')),
    sa.UniqueConstraint('tailor_id', 'package_id', name='uq_tailor_prices_tailor_package')
    )
    with op.batch_alter_table('tailor_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tailor_prices_tailor_id'), ['tailor_id'], unique=False)

    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('placed', 'assigned', 'accepted', 'measurement_done', 'stitching', 'ready', 'delivered', 'cancelled', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('actor_role', sa.Enum('customer', 'tailor', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'void', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('order_id', name=op.f('uq_payments_order_id'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tailor_id', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Integer(), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.Column('net', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', name='settlementstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_settlements_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailors.id'], name=op.f('fk_settlements_tailor_id_tailors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements')),
    sa.UniqueConstraint('order_id', name=op.f('uq_settlements_order_id'))
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_tailor_id'), ['tailor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_tailor_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_status'))

    op.drop_table('settlements')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))

    op.drop_table('payments')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('tailor_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tailor_prices_tailor_id'))

    op.drop_table('tailor_prices')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_tailor_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_executive_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_options_group_id'))

    op.drop_table('options')
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_documents_tailor_id'))

    op.drop_table('kyc_documents')
    with op.batch_alter_table('tailors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tailors_status'))

    op.drop_table('tailors')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_service_id'))

    op.drop_table('packages')
    with op.batch_alter_table('option_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_groups_service_id'))

    op.drop_table('option_groups')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('services')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_phone'))

    op.drop_table('otp_codes')
    op.drop_table('executives')
    # ### end Alembic commands ###
